# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '/'
    weight: 10
  - name: EFA
    url: '/category/efa'
    weight: 20
    main:
      - name: "Pilot 1 Prolific Nov22"
        url: 'post/efa_nov22'
        weight: 10
      - name: "Pilot 2 Prolific Apr23"
        url: 'post/efa_apr23'
        weight: 20
      - name: "Pilot 3 SONA Win/Spr23"
        url: 'post/efa_sona23'
        weight: 30
  - name: CFA
    url: '/category/cfa'
    weight: 30
  - name: Validity
    url: '/category/validity'
    weight: 40
  - name: Exploratory
    url: 'category/exploratory'
    weight: 50



# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
